# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead..

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ehci_pci"
        "ahci"
        "uas"
        "sd_mod"
        "sdhci_pci"
      ];

      kernelModules = [ ];
    };

    kernelModules = [
      "i915"
      "kvm-intel"
      "quiet"                       # tell the kernel to not be verbose
      "rd.systemd.show_status=auto" # disable systemd status messages
      "rd.udev.log_level=3"         # lower the udev log level to show only errors or worse
      # "video=eDP-1:1920x1200@60"
      # "fbcon=nodefer"               # prevent the kernel from blanking plymouth out of the fb
      # "i915.modeset=1"
      # "logo.nologo"                 # disable boot logo if any
    ];
    extraModulePackages = [ ];

    kernel.sysctl = {
      "kernel.pty.max" = 24000;
      "kernel.sysrq" = 1;
      "net.ipv4.tcp_congestion_control" = "westwood"; # sets the TCP congestion control algorithm to Westwood for IPv4 in the Linux kernel.
      "vm.dirty_background_bytes" = 268435456;
      "vm.dirty_bytes" = 536870912;
      "vm.swappiness" = 10;
      "vm.vfs_cache_pressure" = 50;
      # "vm.page-cluster" = 1;
      # "net.core.default_qdisc" = "cake";
    };
  };

  # Define the file systems
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/81da14b4-f15b-4ab4-b0f1-d6c06c42709e";
      fsType = "ext4";
      options = [
        "defaults"            # Applies the default options for mounting.
        "discard"             # Enables the TRIM command for SSDs.
        "noatime"             # Disables updating access times for files.
        "nodiratime"          # Disables updating directory access times.
        "relatime"            # Minimizes the performance impact compared to atime.
        # "errors=remount-ro" # Remounts the file system as read-only in case of errors.
        # "data=ordered"      # Ensures data ordering for reliability and performance.
        # "discard=async"     # Maintains SSD performance over time.
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/CC29-1361";
      fsType = "vfat";
      options = [ "nofail" ];
    };
  };

  powerManagement = {
    cpuFreqGovernor = lib.mkDefault "balanced";

    #---------------------------------------------------------------------------
    # Disable hid driver (gyro/accel) while sleeping for extra power-saving
    #---------------------------------------------------------------------------

    # removes the intel_hid kernel module, which typically handles input from Intel HID devices, such as gyroscope and accelerometer sensors.
    powerDownCommands = ''
      ${pkgs.kmod}/bin/modprobe -r intel_hid
    '';
    # reloads the intel_hid kernel module, re-enabling the Intel HID devices.
    resumeCommands = ''
      ${pkgs.kmod}/bin/modprobe intel_hid
    '';
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/909cd58a-d4f1-422a-a054-f8e096efdd23"; } ];

  networking = {
    useDHCP = lib.mkDefault true;
    # interfaces.enp0s25.useDHCP = lib.mkDefault true;
    # interfaces.wlo1.useDHCP = lib.mkDefault true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  #---------------------------------------------------------------------
  # Hardware Configuration
  #---------------------------------------------------------------------
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableAllFirmware = true;
  };
}